spring:
  datasource:
     url: jdbc:postgresql://localhost:5432/pub
     username: postgres
     password: postgres
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: false
  main:
    allow-circular-references: false

app:
  jobs:
     job-encerrar-eventos:
         cron: ${CRON_JOB_ENCERRAR_EVENTOS:0 * * * * ?}
     job-iniciar-eventos:
         cron: ${CRON_JOB_INICIAR_EVENTOS:30 * * * * ?}

