spring:
  datasource:
     url: jdbc:postgresql://localhost:5432/pub
     username: postgres
     password: postgres
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: false
  main:
    allow-circular-references: false

