ALTER TABLE evento ADD COLUMN IF NOT EXISTS status varchar(100) NOT NULL;

ALTER TABLE evento ADD COLUMN IF NOT EXISTS data_hora_cancelamento TIMESTAMP WITH TIME ZONE;

ALTER TABLE evento ADD COLUMN IF NOT EXISTS data_hora_finalizacao  TIMESTAMP WITH TIME ZONE;


