CREATE TABLE promocao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(255),
    data_inicio TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_fim TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    aplicar_todas_regras BOOLEAN NOT NULL DEFAULT FALSE,
    data_cadastro TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE regra_promocao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(255) NOT NULL,
    meta INTEGER NOT NULL,
    valor_regra NUMERIC NOT NULL,
    tipo_regra VARCHAR(255) NOT NULL,
    produto_gratis_id BIGINT,
    data_cadastro TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE regra_promocao
ADD CONSTRAINT fk_produto_gratis_promocao
FOREIGN KEY (produto_gratis_id)
REFERENCES produto(id);

CREATE TABLE regra_promocao_produto (
    regra_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    CONSTRAINT pk_regra_promocao_produto PRIMARY KEY (regra_id, produto_id),
    CONSTRAINT fk_regra_promocao_regra FOREIGN KEY (regra_id) REFERENCES public.regra_promocao(id),
    CONSTRAINT fk_regra_promocao_produto FOREIGN KEY (produto_id) REFERENCES public.produto(id)
);
