CREATE TABLE atendimento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora_inicio TIMESTAMPTZ,
    data_hora_fim TIMESTAMPTZ,
    status VARCHAR(255)
);

CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    telefone VARCHAR(20),
    cpf VARCHAR(20)
);

CREATE TABLE funcionario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcao VARCHAR(255),
    status VARCHAR(255),
    telefone VARCHAR(20),
    cpf VARCHAR(20),
    nome VARCHAR(255)
);

CREATE TABLE mesa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero INTEGER,
    capacidade INTEGER,
    status VARCHAR(255)
);

CREATE TABLE pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora TIMESTAMPTZ,
    status VARCHAR(255),
    atendimento_id BIGINT,
    FOREIGN KEY (atendimento_id) REFERENCES atendimento(id)
);

CREATE TABLE item_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantidade INTEGER,
    preco_produto NUMERIC,
    preco_total NUMERIC,
    pedido_id BIGINT NOT NULL,
    FOREIGN KEY (pedido_id) REFERENCES pedido(id)
);

CREATE TABLE reserva (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora_inicio TIMESTAMPTZ,
    data_hora_fim TIMESTAMPTZ,
    quantidade_pessoas INTEGER,
    status VARCHAR(255),
    cliente_id BIGINT,
    FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);

CREATE TABLE funcionario_pedido (
    pedido_id BIGINT,
    funcionario_id BIGINT,
    PRIMARY KEY (pedido_id, funcionario_id),
    FOREIGN KEY (pedido_id) REFERENCES pedido(id),
    FOREIGN KEY (funcionario_id) REFERENCES funcionario(id)
);

CREATE TABLE atendimento_mesa (
    atendimento_id BIGINT,
    mesa_id BIGINT,
    PRIMARY KEY (atendimento_id, mesa_id),
    FOREIGN KEY (atendimento_id) REFERENCES atendimento(id),
    FOREIGN KEY (mesa_id) REFERENCES mesa(id)
);

CREATE TABLE atendimento_cliente (
    atendimento_id BIGINT,
    cliente_id BIGINT,
    PRIMARY KEY (atendimento_id, cliente_id),
    FOREIGN KEY (atendimento_id) REFERENCES atendimento(id),
    FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);

CREATE TABLE reserva_mesa (
    reserva_id BIGINT,
    mesa_id BIGINT,
    PRIMARY KEY (reserva_id, mesa_id),
    FOREIGN KEY (reserva_id) REFERENCES reserva(id),
    FOREIGN KEY (mesa_id) REFERENCES mesa(id)
);
